mkdir now: add --ignore-existing option that ignores existing directories

diff --git a/mkdir-now b/mkdir-now
--- a/mkdir-now
+++ b/mkdir-now
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 help() {
-  echo "mkdir-now [--full] [--no-create] [--script|-s] [--name TEXT]"
+  echo "mkdir-now [--full] [--no-create] [--ignore-existing] [--script|-s] [--name TEXT]"
   echo
   echo "    creates a directory named by the current date. F.ex."
   echo
@@ -11,6 +11,7 @@ help() {
   echo "      --script     will only return name of created dir on stdout"
   echo "      -s           same as --script"
   echo "      --no-create  don't create dir, only return name of dir that would be"
+  echo "      --ignore-existing do not error out if directory already exists"
   echo "      --full       create directory with full date, such as"
   echo "                   2010-01-22_20:26/"
   echo "      --name TEXT  will allow you to add so string to the name"
@@ -28,6 +29,7 @@ while [ "$1" != "" ]; do
   case "$1" in
     --full)      FULL="true";      shift                       ;;
     --no-create) NO_CREATE="true"; shift                       ;;
+    --ignore-existing) IGNORE_EXISTING="true"; shift           ;;
     --script)    SCRIPT="true";    shift                       ;;
     -s)          SCRIPT="true";    shift                       ;;
     --name)      NAME="true";      shift; NAME_ADD="$1"; shift ;;
@@ -50,8 +52,10 @@ if [ "$NO_CREATE" == "true" ]; then
   echo "$dir"
   exit 0
 elif [ -e "$dir" ]; then
-  echo "\"$dir\" already exists" >&2
-  exit -2
+  if [ "$IGNORE_EXISTING" != "true" ]; then
+    echo "\"$dir\" already exists" >&2
+    exit -2
+  fi
 else
   # default
   mkdir "$dir"
